### PR TITLE
New singular funcs

### PR DESCRIPTION
**Pull request by raulepure**
Added some basic Singular-Kernel functions to Singular.jl:
For polys: jet, diff and jacobian ideal (jacob)
For general ideals: jet, jacobian matrix (jacob) 
For zerodimensional ideals: vector space dimension (vdim, vector space), vector space basis (kbase), highcorner
For modules: jet

### CODE REVIEW

**Comment by wbhart** [comment]
I see you have docstrings. But could you also pull those docstrings (with @docs) in the relevant .md files in the docs directory.

Also there is still a comma without a space on line 131 of ideal.jl.

Just let me know when you are ready for me to merge it.

**Comment by wbhart** [comment]
Oh, hopefully you can also add an example in the docs as well, following the standard format we have for examples in the .md files.

**Comment by wbhart** [comment]
@heiderich suggested that derivative and jacobi would be better names on the Julia side.

Note derivative is the name we already have in Nemo/AbstractAlgebra, but the interface would have to conform to the interface there if you use that name:

https://nemocas.github.io/AbstractAlgebra.jl/latest/mpolynomial_rings/#Optional-functionality-for-multivariate-polynomials-1

See the section "Derivations". Though at the moment it only allows derivatives with a single variable. It's not at all clear how to support more complicated derivatives. We might need a new data structure for that.

**Comment by heiderich** [comment]
Yes, we have `derivative` now in AbstractAlgebra.jl. The function `jacobi` was finally dropped from 

https://github.com/Nemocas/AbstractAlgebra.jl/pull/102

**Comment by wbhart** [comment]
Note that this PR is based on my previous one, hence the commits from me. It'll look cleaner once my PR is merged of course.

**Pull request closed without merging**
